version: '2'

services:
  app-person-be:
    image: juan321/ms_person_be:latest
    container_name: ms_person_be
    ports:
      - "8081:8081"
  app-product-be:
    image: juan321/ms_product_be:latest
    container_name: ms_product_be
    ports:
      - "8082:8082"
    #environment:
    #  MY_ENVIRONMENT: ${MY_ENVIRONMENT}
    #volumes:
    #  - /ruta/en/el/host:/ruta/en/el/contenedor
